### ISSUE TITLE
Tested hardware

### ISSUE THREAD

**Issue by Partizan7676** [HomeKidd/ESP8266-HomeKit-Paradox-Alarm-System#1]
Thanks for great job! I'll test it with EVO192 system. i think it will work. because it have same ip-module that you test with MG5050. My apologies you use IP-150 ?

**Comment by HomeKidd** [comment]
Thanks! 😄 

Currently you cannot test it because as i've said in the [Readme](https://github.com/HomeKidd/ESP8266-HomeKit-Paradox-Alarm-System/blob/master/README.md): it is just an **"empty" accessory currently and not controlling anything yet**!
Also IP150 (and any extra module) is **not** needed! These are not necessary to communicate with Paradox alarm systems because all of the ESP8266 modules have Wi-Fi built in!
And as an extra info: not all [IP150 modules](https://github.com/Tertiush/ParadoxIP150v2) are working with HomeKit code (eg.: this is why no update for this [homebridge](https://www.npmjs.com/package/homebridge-paradox-security-system) plugin since 2017).
